### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by SplendidAppendix** [joe-herbert/sideloads#1]
First of all, thank you for creating the one thing that I've wanted for forever - a simple way to show downloads in the sidebar!

Is there a way to edit the font size? Because currently they are all rather large, and I can't read the entire file name to see what is what without dragging the sidebar out and extending the width.

**Comment by joe-herbert** [comment]
No problem - it bugged me for ages that there wasn’t an easy way to do it!

I’ve been working on an update which will add a few features, including the ability to change the font size. Before I could finish it though, I left for a trip to Australia - I’m hoping to finish it when I’m home in early September. 

If you want a smaller font size right now, you could always download the code, edit the CSS in  sidebar.html and install it locally as a temporary add-on for the time being. MDN has good resources on this if you haven’t done it before.

**Comment by joe-herbert** [comment]
@SplendidAppendix V2.0 is now available and allows you to edit the font size. If you have any more improvements for the add on, please let me know!
